# Generated by Django 5.1.1 on 2024-09-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default='00', max_length=255),
            preserve_default=False,
        ),
    ]
